name: Build and Package Storybook

on:
  workflow_dispatch: # This makes it manually triggerable from GitHub UI

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./storybook
        run: npm install

      - name: Build Storybook
        working-directory: ./storybook
        run: npm run build-storybook

      - name: Move Storybook static to SCORM folder
        run: |
          mv ./storybook/storybook-static ./storybook-scorm/

      - name: Create Zip Archive
        working-directory: ./
        run: |
          cd storybook-scorm
          zip -r ../storybook-scorm.zip ./*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./storybook-scorm.zip
          tag_name: storybook-${{ github.run_number }}
          name: Storybook SCORM Build ${{ github.run_number }}
          body: Automated Storybook SCORM package build
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
